/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/ping': {
    /** Ping */
    get: operations['ping'];
  };
}

export interface components {
  schemas: {
    PingResponse: {
      status: string;
    };
  };
}

export interface operations {
  /** Ping */
  ping: {
    responses: {
      /** ok */
      200: {
        content: {
          'application/json': components['schemas']['PingResponse'];
        };
      };
    };
  };
}

export interface external {}
